#include "model/Body.h"
#include "model/ChamferBuilder.h"
#include "model/ChamferFeature.h"
#include "model/ChamferToolSession.h"
#include "model/CircularPatternFeature.h"
#include "model/CircularPatternToolSession.h"
#include "model/Document.h"
#include "model/DraftBuilder.h"
#include "model/DraftFeature.h"
#include "model/DraftToolSession.h"
#include "model/EdgeFeatureLimits.h"
#include "model/EdgeManipulatorGeometry.h"
#include "model/ExtrudeFeature.h"
#include "model/ExtrudeOperationDetector.h"
#include "model/ExtrudeSource.h"
#include "model/ExtrudeToolSession.h"
#include "model/FaceExtrudeBuilder.h"
#include "model/Feature.h"
#include "model/FilletBuilder.h"
#include "model/FilletFeature.h"
#include "model/FilletToolSession.h"
#include "model/GeometryOperation.h"
#include "model/IdGeneration.h"
#include "model/ImportedShapeFeature.h"
#include "model/JoinBodiesFeature.h"
#include "model/JoinBodiesToolSession.h"
#include "model/LinearPatternFeature.h"
#include "model/LinearPatternToolSession.h"
#include "model/MirrorFeature.h"
#include "model/MirrorToolSession.h"
#include "model/MoveFeature.h"
#include "model/MoveToolSession.h"
#include "model/NumericParameterState.h"
#include "model/OperationFailure.h"
#include "model/PartDesignToolFramework.h"
#include "model/PatternTypes.h"
#include "model/PocketFeature.h"
#include "model/RevolveFeature.h"
#include "model/RevolveToolSession.h"
#include "model/ShapeContainerUtils.h"
#include "model/ShapeFeature.h"
#include "model/ShellBuilder.h"
#include "model/ShellFeature.h"
#include "model/ShellToolSession.h"
#include "model/SketchExtrudeBuilder.h"
#include "model/SketchPlacement.h"
#include "model/SketchProfileBuilder.h"
#include "model/ToolSession.h"
#include "model/TopologyReference.h"
#include "model/TopologyReferenceResolver.h"
#include "model/macro/MacroDefinition.h"
#include "model/macro/MacroExecutor.h"
#include "model/macro/MacroReferences.h"
#include "sketch/Sketch.h"
#include "sketch/SketchConstraintDiagnostics.h"
#include "sketch/SketchSolver.h"

#include <cstdlib>

static_assert(static_cast<unsigned>(solidar::FeatureKind::ImportedShape) == 1);
static_assert(solidar::kPersistedFeatureKindCount == 13);

int main() { return EXIT_SUCCESS; }
